apiVersion: v1
kind: Service
metadata:
  name: driverservice-srv
spec:
  type: NodePort
  selector:
    app: driverservice
  ports:
  - name: driverservice
    protocol: TCP
    port: 80
    targetPort: 80